In [1]:
import numpy as np

In [2]:
# Creating a numpy array

In [3]:
my_list = [1,2,3]

In [4]:
x = np.array(my_list)

In [5]:
type(x)

numpy.ndarray

In [6]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(1)

array([0.13868085])

In [16]:
np.random.rand(3,3)

array([[0.86197181, 0.96931091, 0.96018991],
       [0.08725611, 0.73975121, 0.048808  ],
       [0.74802522, 0.3926521 , 0.92339611]])

In [17]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr = np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [24]:
arr + 200

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209])

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[0:5] = 100 # broadcasting

In [27]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [28]:
arr = np.arange(1,11)

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])